### ISSUE TITLE
Unit | Component | sl tab panel: setActiveTab() does so correctly 

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1618]
```
Second tab now has active class@ 48 ms
Expected: 	
true
Result: 	
false
Source: 	
    at Object.<anonymous> (http://localhost:4200/assets/tests.js:28305:16)
    at Object.wrapper (http://localhost:4200/assets/test-support.js:38237:29)
    at runTest (http://localhost:4200/assets/test-support.js:2750:28)
    at Object.Test.run (http://localhost:4200/assets/test-support.js:2735:4)
    at http://localhost:4200/assets/test-support.js:2877:11
```

**Comment by erangeles** [comment]
@notmessenger taking this.
