### ISSUE TITLE
Unit | Component | sl tab panel: getInitialTabName() returns the correct tab name

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1619]
```
First tab is initial tab by default@ 48 ms
Expected: 	
"one"
Result: 	
undefined
Source: 	
    at Object.<anonymous> (http://localhost:4200/assets/tests.js:28321:16)
    at Object.wrapper (http://localhost:4200/assets/test-support.js:38237:29)
    at runTest (http://localhost:4200/assets/test-support.js:2750:28)
    at Object.Test.run (http://localhost:4200/assets/test-support.js:2735:4)
    at http://localhost:4200/assets/test-support.js:2877:11
    at process (http://localhost:4200/assets/test-support.js:2537:24)
```

**Comment by erangeles** [comment]
@juwara0 grabbing this.
