### ISSUE TITLE
Unit | Component | sl tab panel: getActiveTabName returns the correct value after setActiveTab() is called (

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1620]
```
failed@ 67 ms
Expected: 	
"two"
Result: 	
undefined
Source: 	
    at Object.<anonymous> (http://localhost:4200/assets/tests.js:28362:16)
    at Object.wrapper (http://localhost:4200/assets/test-support.js:38237:29)
    at runTest (http://localhost:4200/assets/test-support.js:2750:28)
    at Object.Test.run (http://localhost:4200/assets/test-support.js:2735:4)
    at http://localhost:4200/assets/test-support.js:2877:11
    at process (http://localhost:4200/assets/test-support.js:2537:24)
```

**Comment by erangeles** [comment]
@notmessenger taking this.
