### ISSUE TITLE
Error: Attempting to watch missing directory

### ISSUE THREAD

**Issue by georges49** [softlayer/sl-ember-components#1677]
After installing the add-on and running ember server, I get the following error.

The Broccoli Plugin: [Funnel] failed with:
Error: Attempting to watch missing directory: C:\Program Files\Git\ember-panels\
node_modules\sl-ember-components\node_modules\sl-ember-components\app
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (C:\Program Files\Git\e
mber-panels\node_modules\ember-cli\node_modules\broccoli-sane-watcher\index.js:9
0:11)
    at C:\Program Files\Git\ember-panels\node_modules\ember-cli\node_modules\emb
er-cli-broccoli\lib\builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (C:\Program Files\Git\ember-panels\node_modu
les\ember-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Program Files\Git\ember-panels\nod
e_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at C:\Program Files\Git\ember-panels\node_modules\ember-cli\node_modules\rsv
p\dist\rsvp.js:331:11
    at lib$rsvp$asap$$flush (C:\Program Files\Git\ember-panels\node_modules\embe
r-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (C:\Program Files\Git\ember-panels\node_modules\sl-ember-co
mponents\node_modules\broccoli-funnel\node_modules\broccoli-plugin\index.js:7:31
)
    at new Funnel (C:\Program Files\Git\ember-panels\node_modules\sl-ember-compo
nents\node_modules\broccoli-funnel\index.js:44:10)
    at Class.module.exports.treeForVendor (C:\Program Files\Git\ember-panels\nod
e_modules\sl-ember-components\index.js:85:17)
    at Class._treeFor (C:\Program Files\Git\ember-panels\node_modules\ember-cli\
lib\models\addon.js:322:31)
    at Class.treeFor (C:\Program Files\Git\ember-panels\node_modules\ember-cli\l
ib\models\addon.js:290:19)
    at C:\Program Files\Git\ember-panels\node_modules\ember-cli\lib\broccoli\emb
er-app.js:446:20
    at Array.map (native)
    at EmberApp.addonTreesFor (C:\Program Files\Git\ember-panels\node_modules\em
ber-cli\lib\broccoli\ember-app.js:444:30)
    at EmberApp._processedVendorTree (C:\Program Files\Git\ember-panels\node_mod
ules\ember-cli\lib\broccoli\ember-app.js:865:29)
    at EmberApp._processedExternalTree (C:\Program Files\Git\ember-panels\node_m
odules\ember-cli\lib\broccoli\ember-app.js:895:21)

**Comment by notmessenger** [comment]
What version of Node are you running?

**Comment by georges49** [comment]
v5.7.1

**Comment by notmessenger** [comment]
Does running `rm -rf node_modules && npm cache clean && npm install` resolve the issue?

**Comment by georges49** [comment]
I ran the command but there was some errors during. Now when I run ember s, I get a different error:
Error: Could not require 'ember-cli-build.js': Cannot find module 'ember-cli/lib
/broccoli/ember-app'

![broccoli-error](https://cloud.githubusercontent.com/assets/17703137/16089990/4725a0e2-3336-11e6-8173-75645cf3d282.PNG)

**Comment by vlascik** [comment]
same thing here, when I disabled check at `index.js` -> `treeForVendor()` (line 82)
```
var folder = ( Number( process.version.match( /^v(\d+)/ )[1] ) >= 5 ) ? this.name : '../';
```
so that the `folder` was '../', it worked.

ember-cli: 2.8.0-beta.1
node: 6.2.1
os: win32 x64

**Comment by jdhines** [comment]
I have this issue too. I installed `sl-ember-components` at v0.12.3, cleared the npm cache, removed node_modules, and reinstalled everything, and it's giving me this error. I don't know why it's trying to watch this directory (`node_modules/sl-ember-components/node_modules/sl-ember-components/app`), because it doesn't make any sense for a package to have itself in `node_modules` anyway.

**Comment by vlascik** [comment]
@jdhines i think this addon is abandoned, there were no major fixes for at least a year, in the end i just gave up and used ember-bootstrap + bunch of smaller addons.

**Comment by notmessenger** [comment]
@jdhines @vlascik This problem seems related to the same cause of https://github.com/softlayer/ember-cli-jsdoc/issues/19 and https://github.com/softlayer/ember-cli-jsdoc/issues/36.  I don't have time at the moment to test all of the iterations of the code but hope to get a fix in for this soon.

@jdhines This package does not have itself in `node_modules`, it is due to the problem described in the previously-listed issues.  watchman is not watching this directory for any changes, however it does access the directory in order to add LESS-generated CSS into the vendor tree of a consuming app to be imported in `included()`.  More information about this can be found at https://github.com/softlayer/sl-ember-components#styling and https://github.com/softlayer/sl-ember-components/blob/master/index.js#L70-L77

@vlascik This project no longer has full-time development resources being dedicated to it.  Myself and @juwara0, who were the primary contributors, no longer work at SoftLayer, and both SoftLayer and our present employer's focus have shifted away from this library.  I try and keep up with any bugs that are reported, such as making modifications last month to be able to support Ember 2.11.0+.  Both @juwara0 and myself remain very interested in the space and any efforts we contribute to it have been undertaken at https://github.com/ember-forge/ember-forge-ui, though you will notice even that project has not been able to be given full-time attention either.  If you, @jdhines, or others have interest in the promise of what https://github.com/ember-forge/ember-forge-ui can provide (of which a lot has already been written and the architecture proven out) please reach out and we can discuss collaboration.

Thank you for your interest in, and use of, this project.

**Comment by notmessenger** [comment]
I have been able to replicate this problem.

Serving an app when running

* node: v7.8.0
* ember-cli: v2.12.1
* ember-cli-babel: v5.2.4
* sl-ember-components: v0.12.3

there is no problem.  When I upgraded ember-cli-babel to v6.1.0 I encountered this error though

```
Error: Attempting to watch missing directory: /notmessenger/project/node_modules/sl-ember-components/node_modules/sl-ember-components/app
    at Watcher_addWatchDir [as addWatchDir] (/notmessenger/project/node_modules/ember-cli-broccoli-sane-watcher/index.js:142:11)
    at //notmessenger/project/node_modules/broccoli-builder/lib/builder.js:132:35
    at tryCatch (/notmessenger/project/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/notmessenger/project/node_modules/rsvp/dist/rsvp.js:554:13)
    at /notmessenger/project/node_modules/rsvp/dist/rsvp.js:629:16
    at flush (/notmessenger/project/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
